# Generated by Django 2.1.1 on 2018-10-04 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
